### ISSUE TITLE
Permission to access the pre-trained Object detector 

### ISSUE THREAD

**Issue by YapengTian** [rhgao/co-separation#1]
Hi Ruohan,

Nice work again! Could you please give us permission to access the pre-trained object detector? Thanks!

**Comment by rhgao** [comment]
Hi Yapeng,

Thanks for letting me know the permission issue. You should now be able to access the pre-trained models.

Best,
Ruohan

**Comment by manhnguyen1998** [comment]
Hi Ruohan
This pre-trained model was trained for solo videos or multiple source videos (duet...)
I have tested this pretrain but the result with multi source is not the same result in paper?
Could you please share pre-trained model with multiple source.

Thanks
