### ISSUE TITLE
About the config: --scene_path /your_root/hdf5/ADE.h5

### ISSUE THREAD

**Issue by chccgiven** [rhgao/co-separation#2]
Hi !
I want to test on the pre-trained model, but now I'm confused about the config:--scene_path /your_root/hdf5/ADE.h5, could you please tell me what the ADE.h5 is and how can I gain this file?

Thank you very much!

**Comment by rhgao** [comment]
Hi, 

The ADE.h5 file just stores the paths to the scene images in the ADE dataset. A sample file that I used is now shared in this folder:  https://drive.google.com/drive/folders/1K9DdSu7fK0rVmVbdvTgulOwDQHzxbBsK?usp=sharing

Best,
Ruohan

**Comment by chccgiven** [comment]
> Hi,
> 
> The ADE.h5 file just stores the paths to the scene images in the ADE dataset. A sample file that I used is now shared in this folder: https://drive.google.com/drive/folders/1K9DdSu7fK0rVmVbdvTgulOwDQHzxbBsK?usp=sharing
> 
> Best,
> Ruohan

Hi !
Thanks for your kind reply and excellent work!!
Now I'm trying to train your model, but I get the error:
OSError: Unable to open file (unable to open file: name = 'hdf5/soloduet/train.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Could you please tell me what the file train.h5 is? If possible, could you share this file?
Thank you so much again!!!

**Comment by rhgao** [comment]
Hi,

The hdf5 file only contains the relative path to the object detection results. Please see audioVisual_dataset.py L88-90  for how I load the data. You need to prepare your own hdf5 file based on your data to train the model.

I have just shared the sample hdf5 files for your reference in: https://drive.google.com/drive/folders/1K9DdSu7fK0rVmVbdvTgulOwDQHzxbBsK?usp=sharing

Hope that helps.

**Comment by chccgiven** [comment]
> Hi,
> 
> The hdf5 file only contains the relative path to the object detection results. Please see audioVisual_dataset.py L88-90 for how I load the data. You need to prepare your own hdf5 file based on your data to train the model.
> 
> I have just shared the sample hdf5 files for your reference in: https://drive.google.com/drive/folders/1K9DdSu7fK0rVmVbdvTgulOwDQHzxbBsK?usp=sharing
> 
> Hope that helps.

It really helps a lot, thank you for your patient guidance ^^
