### ISSUE TITLE
About the format of .npy file of the object detector output

### ISSUE THREAD

**Issue by CarolXiHang** [rhgao/co-separation#3]
Hi!
I was trying to run the test.py on my own images. So I use the pre-trained detector on my images first and get the result. But I am a little bit confused that it is mentioned in readme.md that each video should have a .npy file to save the object detection result. What is the format that could be load successfully?  
For example, it seems that the format of 1 object could be 
[[frame_name1, ?, confidence_1, [xmin, ymin, xmax, ymax]],
[frame_name2, ?, confidence_2, [xmin, ymin, xmax, ymax]],
.....]
but how can I define the format if there are several objects?

I am a freshman so it confused me a lot. Is there anyone who can help me? Thanks a lot.

**Comment by rhgao** [comment]
Hi sorry for the confusion.

I have just updated README and uploaded a sample script get generate object detection .npy files. 

Each .npy file should contain all the object detections for that video with each detection represented by 7 numbers (frame_index,class_id,confidence_score,four bounding box coordinates).

Hope that helps.
Ruohan

**Comment by CarolXiHang** [comment]
Thanks for your help!
