### ISSUE TITLE
Evaluation Script to Calculate SDR, SIR and SAR

### ISSUE THREAD

**Issue by yangwang4040** [rhgao/co-separation#4]
test.py basically separates two audios from the videos. Can you please share the script to calculate SDR, SIR and SAR on test set?

**Comment by rhgao** [comment]
Sure. evaluateSeparation.py was just uploaded. See README.

**Comment by yangwang4040** [comment]
Thanks. To Calculate SDR, SIR and SAR, did you consider two videos only? Or consider whole test set. Because evaluateSeparation.py considers two audios only. It's not considering whole test set.
