### ISSUE TITLE
Object Class Label Mismatch

### ISSUE THREAD

**Issue by metro-smiles** [rhgao/co-separation#9]
Hi @rhgao ,

Really appreciate your effort in sharing the code! But it seems there might be an issue.

In particular, the pre-trained object detector is trained on these classes: Banjo, Cello, Drum, Guitar, Harp, Harmonica, Oboe, Piano, Saxophone, Trombone, Trumpet, Violin, Flute, Accordion, and Horn
while the classes of the MUSIC dataset (solo) are: accordion, acoustic guitar, cello, clarinet, erhu, flute, saxophone,  trumpet,  tuba,  violin and xylophone.

How are we to deal with classes that appear in MUSIC but not in the pre-trained detector, such as erhu, xylophone, etc.?

Any help would be much appreciated.

**Comment by rhgao** [comment]
Hi @metro-smiles , the pre-trained object detector is pre-trained on the OpenImages dataset, so the classes are not exactly matched with the classess in MUSIC dataset. However, the pre-trained object detector can still be used to detect objects (though it might predict a different class, say a visually similar class, for categories that are not matched). The detected objects can still be used to provide supervision for co-separation. Therefore, the system can sometimes map an object to a wrong class, but still be able to separate their sounds.
